Repository hassio-addons/addon-appdaemon, pull requests merged in 2021-02, with the labels that each got.

#72 Upgrade add-on base image to 9.1.2
  appdaemon/Dockerfile
  appdaemon/build.json
Labels: dependencies

#74 Raise fatal error message on missing AppDaemon configuration file
  appdaemon/rootfs/etc/cont-init.d/appdaemon.sh
Labels: enhancement

#78 Update add-on configuration for Supervisor 2021.2
  .github/workflows/ci.yaml
  appdaemon/config.json
Labels: maintenance

#79 Make transparent logo
  appdaemon/logo.png
Labels: enhancement

#82 Upgrade add-on base image to 9.1.4
  appdaemon/Dockerfile
  appdaemon/build.json
Labels: dependencies

#84 :arrow_up: Upgrades python3 to 3.8.7-r1
  appdaemon/Dockerfile
Labels: dependencies
